"""create assessment records

Revision ID: de79461b447f
Revises: 1b27141e06b0
Create Date: 2026-09-11 19:21:40.073530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de79461b447f'
down_revision: Union[str, Sequence[str], None] = '1b27141e06b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pilot_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('benchmark_id', sa.String(length=100), nullable=False),
    sa.Column('benchmark_version', sa.String(length=50), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('max_altitude_ft', sa.Float(), nullable=False),
    sa.Column('min_altitude_ft', sa.Float(), nullable=False),
    sa.Column('max_speed_knots', sa.Float(), nullable=False),
    sa.Column('avg_speed_knots', sa.Float(), nullable=False),
    sa.Column('max_pitch_deg', sa.Float(), nullable=False),
    sa.Column('min_pitch_deg', sa.Float(), nullable=False),
    sa.Column('max_roll_deg', sa.Float(), nullable=False),
    sa.Column('min_roll_deg', sa.Float(), nullable=False),
    sa.Column('max_bank_angle_deg', sa.Float(), nullable=False),
    sa.Column('max_climb_rate_fpm', sa.Float(), nullable=False),
    sa.Column('max_descent_rate_fpm', sa.Float(), nullable=False),
    sa.Column('avg_throttle_percent', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('overall_rating', sa.String(length=20), nullable=False),
    sa.Column('benchmark_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visual_observations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('telemetry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_records_created_by'), 'assessment_records', ['created_by'], unique=False)
    op.create_index(op.f('ix_assessment_records_pilot_id'), 'assessment_records', ['pilot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_records_pilot_id'), table_name='assessment_records')
    op.drop_index(op.f('ix_assessment_records_created_by'), table_name='assessment_records')
    op.drop_table('assessment_records')
    # ### end Alembic commands ###
